function onCreate()
  --background
  makeLuaSprite('back','cup/CH-RN-00',-1050,-750)
  scaleObject('back',3.5,3.5)
  setScrollFactor('back',0.4,0.4)
  makeLuaSprite('mid','cup/CH-RN-01',-1050,-600)
  scaleObject('mid',3.5,3.5)
  setScrollFactor('mid',0.4,0.4)
  makeLuaSprite('floor','cup/CH-RN-02',-1050,-750)
  scaleObject('floor',3.5,3.5)
  makeAnimatedLuaSprite('camera','cup/oldtimey',0,0)
  addAnimationByPrefix('camera','idle','Cupheadshit_gif instance 1',24,true)
  objectPlayAnimation('camera','idle',true)
  setObjectCamera('camera','hud')
  makeAnimatedLuaSprite('rain','cup/rain',0,0)
  addAnimationByPrefix('rain','idle','RainFirstlayer instance 1',15,true)
  objectPlayAnimation('rain','idle',true)
  setObjectCamera('rain','hud')
  addLuaSprite('back',false)
  addLuaSprite('mid',false)
  addLuaSprite('floor',false)
  addLuaSprite('rain',false)
  addLuaSprite('camera',true)
  close(true);
  end